name: "Build backend, run linters, unit and integration tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.45
        only-new-issues: true
        skip-go-installation: true

  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Run unit-tests
      run: make test

    - name: Prepare for integration tests
      run: ./deploy.sh

    - name: Run integration tests
      run: make integration-test
